alias ll='ls -l'
alias fhere='find . -iname '
alias zshenv='source ~/.zshenv'
alias vimrc='vi ~/.vimrc'
alias vimzsh='vi ~/.zshenv'
alias rsyncf='rsync -rtl --progress  --stats --exclude .git --exclude lib --exclude obj --exclude bmstmp --exclude hotel_cmk --exclude dba'
alias rsyncRtm='time rsyncf /home/vagrant/workspace/amadeus/rates/rtm gverma@bossrnd112173.dev.wlm.amadeus.net:$HOME/workspace/amadeus/rates'
alias docker='sudo docker'
alias psmy='ps -fu $USER | sort | egrep -v "ps -fu|sort|grep"'
alias tfresh='rm -rf tags && ctags -R *'

alias rtm='$HOME/workspace/amadeus/rates/rtm/src'
alias rtp='$HOME/workspace/amadeus/rates/rtp/src'
alias rpp='$HOME/workspace/amadeus/rates/rpp'
alias regsf='~/workspace/amadeus/rates/ridTools/reg/runreg.py -f'
alias log='/data/gverma/cmk/oberoot/com/log'
alias fig='$HOME/workspace/amadeus/rates/rtm/regression/main/dev/Figaro'
alias helper='python $HOME/tools/scripts/scripts/work/helper.py'
alias cleanit='helper --clean'
alias connect='helper --connect'
alias fastnas='/remote/tmp/users_workplace/gverma'
alias fhere='find . -iname'
alias ls='ls --color'
alias activatepy='. ~/.pyenvgv/bin/activate'
alias unittest='sh ~/workspace/amadeus/rates/ridTools/unittests/pretty_unit_tests.sh'
alias notify='mail -r "cerberus@BOSVM" -s "Build Complete." gaurav.verma@amadeus.com <<< "Build is complete dude."'
alias cleanbuild='cleanit && bms clean && bms build -b -j48 && cmk install -c rtm && cmk start && notify'
alias initregs='regsf 01_Init  -f 02_TestHelpers  -f 03_spawnBackendInstances'
alias ridtools='cd $HOME/workspace/amadeus/rates/ridTools'
alias searchtag='vim -t '
alias vimrc='vi ~/.vimrc'
alias testdba='./tools/cleanAfterTest.sh && ./tools/testLatestVersion.sh && grep "All good" '
alias lqsadmin='sh /data/gverma/cmk/oberoot/lqs/shell/lqs_admin.sh'
alias lqshelp='cat ~/.lqshelper'
alias lqshelp='cat ~/.lqshelper'


source "$HOME/.vim/plugmanager/gruvbox/gruvbox_256palette.sh"
export PATH=/home/vagrant/bin:$PATH
